from pathlib import Path

from decouple import config

DISCORD_TOKEN = config("DISCORD_TOKEN")
DISCORD_SERVER_ID = config("DISCORD_SERVER_ID")
DISCORD_ATTENTEE_ROLE_NAME = config("DISCORD_ATTENTEE_ROLE_NAME")
DISCORD_WELCOME_CHANNEL = config("DISCORD_WELCOME_CHANNEL")

EVENTBRITE_TOKEN = config("EVENTBRITE_TOKEN")
EVENTBRITE_EVENT_ID = config("EVENTBRITE_EVENT_ID")

ATTENDEES_CACHE_PATH = config(
    "ATTENDEES_INDEX_CACHE", default="/tmp/pybr2022-attendees-cache.json", cast=Path
)

ATTENDEES_CACHE_ENABLED = config("ATTENDEES_CACHE_ENABLED", default=False, cast=bool)

PRETALX_EVENT_SLUT = config("PRETALX_EVENT_SLUT")
PRETALX_TOKEN = config("PRETALX_TOKEN")

DISCORD_ROOM_KEYNOTE = config("DISCORD_ROOM_KEYNOTE", cast=int)
DISCORD_ROOM_ARUANA = config("DISCORD_ROOM_ARUANA", cast=int)
DISCORD_ROOM_TUCUNARE = config("DISCORD_ROOM_TUCUNARE", cast=int)
DISCORD_ROOM_JARAQUI = config("DISCORD_ROOM_JARAQUI", cast=int)